version: '3.3'
services:

  web:
    build: web
    ports: 
      - 5000:5000
    links: 
      - sql
    depends_on: 
      - sql

  sql:
    build: sql
    ports: 
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql
